baseURL = "https://reviewerowl.com/"  # Update with your domain
languageCode = "en-us"
title = "Reviewer Owl | The Wise Reviewer"
theme = "stack"
defaultContentLanguage = "en"
hasCJKLanguage = false

# Google Analytics
googleAnalytics = "G-GLMX68KSDS"  # Your GA4 ID

# Content settings
[content]
  [content.snippets]
    wordCount = 280  # For summary generation

# Pagination
[pagination]
  pagerSize = 5  # Matches your YAML config


# Build optimizations
[build]
  useResourceCacheWhen = "fallback"
  writeStats = true  # Helps with debugging

[outputs]
  home = ["HTML", "RSS"]  # Basic output formats

  # Disqus comments
disqusShortname = "reviewerowl"

