# Core Settings
mainSections = ["posts"]
rssFullContent = true
favicon = "/favicon.png"

# Branding
[sidebar]
  # emoji = "🦉"
  subtitle = "Honest Reviews for Books, Food & Beyond"
  [sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"
    
# Add this section to control menu behavior
[menu]
  mainWeight = 100  # Base weight for main menu items
  socialWeight = 200 # Base weight for social menu items

# Update your sidebar widgets configuration
[sidebar]
  widgets = ["search", "archives", "categories", "tag-cloud"]  # Exact order you want
  [sidebar.widgetsConfig]
    [sidebar.widgetsConfig.archives]
      limit = 5
    [sidebar.widgetsConfig.categories]
      limit = 10
    [sidebar.widgetsConfig.tag-cloud]
      limit = 10

# Content Display
[article]
  headingAnchor = false
  math = false
  readingTime = true
  [article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

# Date Formatting (unchanged)
[dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

# Footer (updated)
[footer]
  since = 2024
  customText = "🦉 Wise reviews for discerning readers (and eaters!)"

# Homepage Widgets (updated)
## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

# OpenGraph/Twitter Cards (unchanged)
[opengraph.twitter]
  card = "summary_large_image"


# Color Scheme (unchanged)
[colorScheme]
  toggle = true
  default = "auto"

# Image Processing (unchanged)
[imageProcessing]
  [imageProcessing.cover]
    enabled = true
  [imageProcessing.content]
    enabled = true
