# Core Settings
mainSections = ["posts"]
rssFullContent = true
favicon = "/favicon.png"

# Branding & Display
[sidebar]
  subtitle = "Honest Reviews for Books, Food & Beyond"
  [sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"
  
  # Widgets Configuration (Moved from homepage widgets)
  widgets = ["search", "archives", "categories", "tag-cloud"]
  [sidebar.widgetsConfig]
    [sidebar.widgetsConfig.archives]
      limit = 5
    [sidebar.widgetsConfig.categories]
      limit = 10
    [sidebar.widgetsConfig.tag-cloud]
      limit = 10

# Menu Configuration
[menu]
  mainWeight = 100  # Base weight for main menu items
  socialWeight = 200 # Base weight for social menu items

# Content Settings
[article]
  headingAnchor = false
  math = false
  readingTime = true
  [article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

# Date Formatting
[dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

# Footer
[footer]
  since = 2024
  customText = "🦉 Wise reviews for discerning readers (and eaters!)"

# Homepage Widgets (Deprecated - moved to sidebar)
# Note: These are kept for backward compatibility but won't be used
# since we've moved widgets to the sidebar section above

# UI Settings
[colorScheme]
  toggle = true
  default = "auto"

# Image Processing
[imageProcessing]
  [imageProcessing.cover]
    enabled = true
  [imageProcessing.content]
    enabled = true
